[package]
name = "nlang-interpreter"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
tempfile = "3.3"

[[test]]
name = "list_p25_test"
path = "tests/list_p25_test.rs"

[[test]]
name = "str_p25_test"
path = "tests/str_p25_test.rs"

[[test]]
name = "option_result_p26_test"
path = "tests/option_result_p26_test.rs"

[[test]]
name = "math_p27_test"
path = "tests/math_p27_test.rs"

[[test]]
name = "str_p27_test"
path = "tests/str_p27_test.rs"

[[test]]
name = "list_p28_test"
path = "tests/list_p28_test.rs"

[[test]]
name = "str_format_p29_test"
path = "tests/str_format_p29_test.rs"

[[test]]
name = "bytes_p30_test"
path = "tests/bytes_p30_test.rs"

[[test]]
name = "regex_p31_test"
path = "tests/regex_p31_test.rs"

[[test]]
name = "bytes_crypto_p32_test"
path = "tests/bytes_crypto_p32_test.rs"

[[test]]
name = "str_p32_test"
path = "tests/str_p32_test.rs"

[[test]]
name = "json_p33_test"
path = "tests/json_p33_test.rs"

[[test]]
name = "io_p34_test"
path = "tests/io_p34_test.rs"

[[test]]
name = "list_p35_test"
path = "tests/list_p35_test.rs"

[[test]]
name = "math_p35_test"
path = "tests/math_p35_test.rs"

[[test]]
name = "env_p36_test"
path = "tests/env_p36_test.rs"

[[test]]
name = "process_p36_test"
path = "tests/process_p36_test.rs"

[[test]]
name = "path_p37_test"
path = "tests/path_p37_test.rs"

[[test]]
name = "engine_p39_test"
path = "tests/engine_p39_test.rs"

[dependencies]
regex = "1"
nlang-parser = { path = "../parser" }
thiserror = "1.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indexmap = { version = "=2.5.0", features = ["serde"] }
hashbrown = "0.14"
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.10"
hex = "0.4"
ring = "0.17"
num-bigint = { version = "0.4", features = ["serde"] }
num-traits = "0.2"
