//! Builtin key contracts (O76 / O78 ②).
//!
//! Lives in the registry, not in a builtin's value — putting the
//! declaration on the value would move the standard-root digest
//! and with it every root (O58). The spec defines the shape;
//! `contract_for` answers "which keys does this builtin bind?"
//! without running it.

use crate::value::Value;
use std::collections::HashMap;
use std::sync::OnceLock;

/// Keys a builtin binds. Extra keys on the argument (pipe wrap,
/// lifted names the builtin does not bind) are ignored; missing
/// required keys are a mismatch (apply layer → `Value::Top` → cocoon).
#[derive(Clone, Copy, Debug)]
pub struct BuiltinContract {
    pub required: &'static [&'static str],
}

impl BuiltinContract {
    pub fn satisfied(self, unified: &Value) -> bool {
        if self.required.is_empty() {
            return true;
        }
        match unified {
            Value::Combo(c) => self.required.iter().all(|k| c.get_field(k).is_some()),
            _ => false,
        }
    }
}

const RAW: &[(&str, &[&str])] = &[
    ("bytes.at", &["0", "1"] as &[_]),
    ("bytes.base64_decode", &["0"] as &[_]),
    ("bytes.base64_encode", &["0"] as &[_]),
    ("bytes.concat", &["0", "1"] as &[_]),
    ("bytes.from_hex", &["0"] as &[_]),
    ("bytes.from_str", &["0"] as &[_]),
    ("bytes.hmac_sha256", &["0", "1"] as &[_]),
    ("bytes.len", &["0"] as &[_]),
    ("bytes.sha256", &["0"] as &[_]),
    ("bytes.slice", &["0", "1", "2"] as &[_]),
    ("bytes.to_hex", &["0"] as &[_]),
    ("bytes.to_str", &["0"] as &[_]),
    ("complex.conj", &["0"] as &[_]),
    ("complex.imag", &["0"] as &[_]),
    ("complex.phase", &["0"] as &[_]),
    ("complex.real", &["0"] as &[_]),
    ("cond.cond", &["0"] as &[_]),
    ("cond.if", &["0", "1", "2"] as &[_]),
    ("cond.match", &["0", "1"] as &[_]),
    ("csv.parse", &["0"] as &[_]),
    ("csv.parse_with_headers", &["0"] as &[_]),
    ("csv.read_csv", &["0"] as &[_]),
    ("csv.stringify", &[] as &[_]),
    ("diff.diff", &["0", "1"] as &[_]),
    ("diff.is_compatible", &["0", "1"] as &[_]),
    ("diff.patch", &["0", "1"] as &[_]),
    ("disc.advertise", &[] as &[_]),
    ("disc.connect", &["0", "1"] as &[_]),
    ("disc.fetch", &["0"] as &[_]),
    ("disc.find", &[] as &[_]),
    ("disc.identify", &[] as &[_]),
    ("effect.run_pure", &["0"] as &[_]),
    ("engine.check_oml", &["a", "b"] as &[_]),
    ("engine.differential", &[] as &[_]),
    ("engine.equivalence_map", &[] as &[_]),
    ("engine.observe", &[] as &[_]),
    ("engine.project_down", &["target", "masa"] as &[_]),
    ("engine.project_up", &["sections"] as &[_]),
    ("engine.resolve", &["0"] as &[_]),
    ("engine.save", &[] as &[_]),
    ("engine.set_strategy", &["strategy"] as &[_]),
    ("env.args", &[] as &[_]),
    ("env.cwd", &[] as &[_]),
    ("env.get", &["0"] as &[_]),
    ("io.append_file", &["0", "1"] as &[_]),
    ("io.exists", &["0"] as &[_]),
    ("io.read_file", &["0"] as &[_]),
    ("io.write_file", &["0", "1"] as &[_]),
    ("json.get", &["0", "1"] as &[_]),
    ("json.keys", &["0"] as &[_]),
    ("json.parse", &["0"] as &[_]),
    ("json.stringify", &["0"] as &[_]),
    ("list.all", &["0", "1"] as &[_]),
    ("list.any", &["0", "1"] as &[_]),
    ("list.at", &["0", "1"] as &[_]),
    ("list.chunk", &["0", "1"] as &[_]),
    ("list.concat", &["0", "1"] as &[_]),
    ("list.count", &["0", "1"] as &[_]),
    ("list.dedup", &["0"] as &[_]),
    ("list.drop", &["0", "1"] as &[_]),
    ("list.drop_while", &["0", "1"] as &[_]),
    ("list.enumerate", &["0"] as &[_]),
    ("list.filter", &["0", "1"] as &[_]),
    ("list.find", &["0", "1"] as &[_]),
    ("list.flat_map", &["0", "1"] as &[_]),
    ("list.flatten", &["0"] as &[_]),
    ("list.fold", &["0", "1"] as &[_]),
    ("list.group_by", &["0", "1"] as &[_]),
    ("list.head", &["0"] as &[_]),
    ("list.intersperse", &["0", "1"] as &[_]),
    ("list.len", &["0"] as &[_]),
    ("list.map", &["0", "1"] as &[_]),
    ("list.max_by", &["0", "1"] as &[_]),
    ("list.min_by", &["0", "1"] as &[_]),
    ("list.partition", &["0", "1"] as &[_]),
    ("list.product", &["0"] as &[_]),
    ("list.range", &["0", "1"] as &[_]),
    ("list.reduce", &["0", "1"] as &[_]),
    ("list.reverse", &["0"] as &[_]),
    ("list.scan", &["0", "1", "2"] as &[_]),
    ("list.slice", &["0", "1", "2"] as &[_]),
    ("list.sort", &["0"] as &[_]),
    ("list.sort_by", &["0", "1"] as &[_]),
    ("list.sum", &["0"] as &[_]),
    ("list.tail", &["0"] as &[_]),
    ("list.take", &["0", "1"] as &[_]),
    ("list.take_while", &["0", "1"] as &[_]),
    ("list.transpose", &["0"] as &[_]),
    ("list.unique", &["0"] as &[_]),
    ("list.window", &["0", "1"] as &[_]),
    ("list.zip", &["0", "1"] as &[_]),
    ("list.zip_with", &["0", "1", "2"] as &[_]),
    ("math.abs", &["0"] as &[_]),
    ("math.add", &["0", "1"] as &[_]),
    ("math.atan2", &["0", "1"] as &[_]),
    ("math.bits", &["0"] as &[_]),
    ("math.ceil", &["0"] as &[_]),
    ("math.choose", &["0", "1"] as &[_]),
    ("math.clamp", &["0", "1", "2"] as &[_]),
    ("math.cos", &["0"] as &[_]),
    ("math.cosh", &["0"] as &[_]),
    ("math.div", &["0", "1"] as &[_]),
    ("math.eml", &["0", "1"] as &[_]),
    ("math.exp", &["0"] as &[_]),
    ("math.factorial", &["0"] as &[_]),
    ("math.floor", &["0"] as &[_]),
    ("math.fract", &["0"] as &[_]),
    ("math.gcd", &["0", "1"] as &[_]),
    ("math.gt", &["0", "1"] as &[_]),
    ("math.gte", &["0", "1"] as &[_]),
    ("math.hypot", &["0", "1"] as &[_]),
    ("math.is_prime", &["0"] as &[_]),
    ("math.lcm", &["0", "1"] as &[_]),
    ("math.ln", &["0"] as &[_]),
    ("math.lt", &["0", "1"] as &[_]),
    ("math.lte", &["0", "1"] as &[_]),
    ("math.log10", &["0"] as &[_]),
    ("math.log2", &["0"] as &[_]),
    ("math.max", &["0", "1"] as &[_]),
    ("math.min", &["0", "1"] as &[_]),
    ("math.mul", &["0", "1"] as &[_]),
    ("math.pow", &["0", "1"] as &[_]),
    ("math.pow_mod", &["0", "1", "2"] as &[_]),
    ("math.random", &[] as &[_]),
    ("math.rem", &["0", "1"] as &[_]),
    ("math.round", &["0"] as &[_]),
    ("math.sign", &["0"] as &[_]),
    ("math.sin", &["0"] as &[_]),
    ("math.sinh", &["0"] as &[_]),
    ("math.sqrt", &["0"] as &[_]),
    ("math.sub", &["0", "1"] as &[_]),
    ("math.tanh", &["0"] as &[_]),
    ("math.to_float", &["0"] as &[_]),
    ("math.trunc", &["0"] as &[_]),
    ("option.and_then", &["0", "1"] as &[_]),
    ("option.expect", &["0", "1"] as &[_]),
    ("option.filter", &["0", "1"] as &[_]),
    ("option.flatten", &["0"] as &[_]),
    ("option.map", &["0", "1"] as &[_]),
    ("option.or", &["0", "1"] as &[_]),
    ("option.unwrap_or", &["0", "1"] as &[_]),
    ("option.zip", &["0", "1"] as &[_]),
    ("path.basename", &["0"] as &[_]),
    ("path.dirname", &["0"] as &[_]),
    ("path.extension", &["0"] as &[_]),
    ("path.is_absolute", &["0"] as &[_]),
    ("path.join", &["0", "1"] as &[_]),
    ("process.exit", &["0"] as &[_]),
    ("process.pid", &[] as &[_]),
    ("query.deep_merge", &["0", "1"] as &[_]),
    ("query.pluck", &["0", "1"] as &[_]),
    ("query.select", &["0"] as &[_]),
    ("query.where", &["0", "1"] as &[_]),
    ("refl.bottom_cause", &["0"] as &[_]),
    ("refl.delete", &["0", "1"] as &[_]),
    ("refl.entries", &["0"] as &[_]),
    ("refl.get", &["0", "1"] as &[_]),
    ("refl.has", &["0", "1"] as &[_]),
    ("refl.is_blur", &["0"] as &[_]),
    ("refl.is_bottom", &["0"] as &[_]),
    ("refl.is_cocoon", &["0"] as &[_]),
    ("refl.is_err", &["0"] as &[_]),
    ("refl.is_none", &["0"] as &[_]),
    ("refl.is_ok", &["0"] as &[_]),
    ("refl.is_some", &["0"] as &[_]),
    ("refl.keys", &["0"] as &[_]),
    ("refl.set", &["0", "1", "2"] as &[_]),
    ("refl.to_str", &["0"] as &[_]),
    ("refl.type_of", &["0"] as &[_]),
    ("refl.values", &["0"] as &[_]),
    ("regex.find", &["0", "1"] as &[_]),
    ("regex.match", &["0", "1"] as &[_]),
    ("regex.replace", &["0", "1", "2"] as &[_]),
    ("regex.split", &["0", "1"] as &[_]),
    ("result.and", &["0", "1"] as &[_]),
    ("result.and_then", &["0", "1"] as &[_]),
    ("result.expect", &["0", "1"] as &[_]),
    ("result.flatten", &["0"] as &[_]),
    ("result.map", &["0", "1"] as &[_]),
    ("result.map_err", &["0", "1"] as &[_]),
    ("result.or", &["0", "1"] as &[_]),
    ("result.unwrap", &[] as &[_]),
    ("set.contains", &["0", "1"] as &[_]),
    ("set.difference", &["0", "1"] as &[_]),
    ("set.from_list", &[] as &[_]),
    ("set.intersection", &["0", "1"] as &[_]),
    ("set.is_disjoint", &["0", "1"] as &[_]),
    ("set.is_subset", &["0", "1"] as &[_]),
    ("set.is_superset", &["0", "1"] as &[_]),
    ("set.union", &["0", "1"] as &[_]),
    ("stat.histogram", &["0", "1"] as &[_]),
    ("stat.mean", &[] as &[_]),
    ("stat.median", &[] as &[_]),
    ("stat.percentile", &["0", "1"] as &[_]),
    ("stat.std_dev", &[] as &[_]),
    ("stat.variance", &[] as &[_]),
    ("str.char_at", &["0", "1"] as &[_]),
    ("str.chars", &["0"] as &[_]),
    ("str.concat", &["0", "1"] as &[_]),
    ("str.contains", &["0", "1"] as &[_]),
    ("str.count", &["0", "1"] as &[_]),
    ("str.decode_uri", &["0"] as &[_]),
    ("str.encode_uri", &["0"] as &[_]),
    ("str.ends_with", &["0", "1"] as &[_]),
    ("str.format", &["0", "1"] as &[_]),
    ("str.from_int", &["0"] as &[_]),
    ("str.index_of", &["0", "1"] as &[_]),
    ("str.is_empty", &["0"] as &[_]),
    ("str.join", &["0", "1"] as &[_]),
    ("str.len", &["0"] as &[_]),
    ("str.levenshtein", &["0", "1"] as &[_]),
    ("str.lines", &["0"] as &[_]),
    ("str.pad_left", &["0", "1"] as &[_]),
    ("str.pad_right", &["0", "1"] as &[_]),
    ("str.parse_float", &["0"] as &[_]),
    ("str.parse_int", &["0"] as &[_]),
    ("str.repeat", &["0", "1"] as &[_]),
    ("str.replace", &["0", "1", "2"] as &[_]),
    ("str.reverse", &["0"] as &[_]),
    ("str.slice", &["0", "1", "2"] as &[_]),
    ("str.split", &["0", "1"] as &[_]),
    ("str.starts_with", &["0", "1"] as &[_]),
    ("str.title_case", &["0"] as &[_]),
    ("str.to_lower", &["0"] as &[_]),
    ("str.to_upper", &["0"] as &[_]),
    ("str.trim", &["0"] as &[_]),
    ("str.trim_end", &["0"] as &[_]),
    ("str.trim_start", &["0"] as &[_]),
    ("str.word_count", &["0"] as &[_]),
    ("time.add_days", &["0", "1"] as &[_]),
    ("time.add_hours", &["0", "1"] as &[_]),
    ("time.add_ms", &["0", "1"] as &[_]),
    ("time.diff", &["0", "1"] as &[_]),
    ("time.format", &["0", "1"] as &[_]),
    ("time.now", &[] as &[_]),
    ("time.parse", &["0", "1"] as &[_]),
    ("time.to_iso8601", &["0"] as &[_]),
    ("time.weekday", &["0"] as &[_]),
    ("toml.parse", &["0"] as &[_]),
    ("toml.stringify", &["0"] as &[_]),
    ("url.decode", &["0"] as &[_]),
    ("url.encode", &["0"] as &[_]),
    ("url.join", &["0", "1"] as &[_]),
    ("url.parse", &["0"] as &[_]),
    ("url.query_params", &["0"] as &[_]),
];

fn table() -> &'static HashMap<&'static str, BuiltinContract> {
    static T: OnceLock<HashMap<&'static str, BuiltinContract>> = OnceLock::new();
    T.get_or_init(|| {
        RAW.iter()
            .map(|(id, keys)| (*id, BuiltinContract { required: keys }))
            .collect()
    })
}

/// Look up the declared keys for a builtin id.
pub fn contract_for(id: &str) -> Option<BuiltinContract> {
    table().get(id).copied()
}

/// Every id in the contract table (for the bijection test).
pub fn contract_ids() -> impl Iterator<Item = &'static str> {
    table().keys().copied()
}
